[package]
name = "akimbo"
version = "1.0.0"
edition = "2021"
authors = ["Jamie Whiting"]

[profile.release]
strip = true
panic = "abort"

[features]
datagen = ["bulletformat"]
tuning = []

[dependencies]
bulletformat = { version = "0.1.0", optional = true }
