[package]
name = "akimbo"
version = "0.8.0"
edition = "2021"
authors = ["Jamie Whiting"]

[profile.release]
strip = true
panic = "abort"

[features]
datagen = ["bulletformat"]

[dependencies]
bulletformat = { version = "0.1.0", optional = true }
