[package]
name = "akimbo"
version = "0.7.0"
edition = "2021"
authors = ["Jamie Whiting"]

[profile.release]
strip = true
panic = "abort"

[features]
default = ["datagen"]
datagen = ["bulletformat"]

[dependencies]
bulletformat = { git = 'https://github.com/jw1912/bulletformat', optional = true}
